### ISSUE TITLE
Mac（M1）打包window提示找不到background.js，打包Mac版本正常，

### ISSUE THREAD

**Issue by Jay0928** [lqsong/electron-admin-element-vue#3]
![Uploading image.png…]()

**Comment by lqsong** [comment]
window版本请在window系统打包

**Comment by Jay0928** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jay0928** [comment]
> window版本请在window系统打包

问题已修复，谢谢
